### ISSUE TITLE
ERROR while reading mesh

### ISSUE THREAD

**Issue by cogitas3d** [s-weisser/surface-segmentation#2]
Hey there!

I'm trying to do the segmentation using a file I created here.

First I tryied to export diretcly from Blender, but the ,msh had an ASCII error.

After, I use Gmsh to export a STL file exporter from Blender:

`./SegmentBM meshes/arcada2.msh -o test.vtk`

ANd I had this error:

> Surface Segmentation
> by Sergej Rjasanow and Steffen Weisser
> Saarland University, Germany, 2018
> Copyright (C) 2018 Steffen Weisser - All Rights Reserved
> 
> Reading geometry from mesh file "meshes/arcada2.msh"
> ERROR while reading mesh.

Can you help me fix this?

**Comment by s-weisser** [comment]
Thank's for your interest in our code!

Obviously, there is some conflict with the mesh file. There are two most probable issues here:
- The msh-file has to be in the ASCII format.
- Our code only supports triangles within the surface mesh in the current version.

If this does not solve your error, one should have a closer look at the return value of the function ReadMesh() in Geometry.c. This function is written on our own and reads only the basic information from msh-files. We collect the node data in the $Nodes block and read the triangles in the $Elements block.

I hope this answer helps you. If not, please feel free to ask for more help or provide one of your msh-files.

**Comment by cogitas3d** [comment]
Hi @s-weisser !

Thanks for your attention! I used gmsh to export link ASCII but had an error on the core (I tink it is the same English message "Segmentation fault (core dumped)"):

```
Surface Segmentation
by Sergej Rjasanow and Steffen Weisser
Saarland University, Germany, 2018
Copyright (C) 2018 Steffen Weisser - All Rights Reserved

Reading geometry from mesh file "meshes/monkey_stl.msh"
SegmentBM: Geometry.c:268: FindEdgesAndNeighbours: Assertion `tria != NULL' failed.
Abortado (imagem do núcleo gravada)
```

**Comment by cogitas3d** [comment]
![captura de tela de 2019-01-02 12-53-44](https://user-images.githubusercontent.com/2422483/50599649-748bb000-0e8d-11e9-8350-9d68ff2163ad.png)
I discovered the problem! The mesh I used is the Monkey of Blender, and it is in really three separated objects: the head and the eyes.

I erased the eyes and close the holes. I exported to gmsh and run.. and it works! Thank you very much!
